AppBlog/urls.py
from django.urls import path
from AppBlog.views import *


urlpatterns = [
    path('pages', home, name="Home"),
    path('posts', posts, name="Posts"),
    path('pages/<int:post_id>', post, name="Posteo"),
    path('borrarpost/<int:post_id>', borrar_post, name="BorrarPost"),
    path('comentarpost/<int:post_id>', comentar_post, name="ComentarPost"),
    path('borrarcomentario/<int:comentario_id>', borrar_comentario, name="BorrarComentario"),
    path('respondercomentario/<int:comentario_id>', responder_comentario, name="ResponderComentario"),
    path('borrarrespuesta/<int:comentario_id>', borrar_respuesta, name="BorrarRespuesta"),
    path('accounts/profile', perfil, name="VerPerfil"),
    path('accounts/profile/edit', editar_datos, name="EditarDatos"),
    path('accounts/profile/editpwd', cambiar_contrasenia, name="CambiarContrasenia"),
    path('about', acerca_de, name="AcercaDe")
]

ProyectoBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('AppLogin.urls')),
    path('blog/', include('AppBlog.urls')),
]

AppBlog/models.py
from django.db import models
import datetime

# Create your models here.

class Posteo(models.Model):
    titulo=models.CharField(max_length=256)
    imagen=models.FileField(upload_to='imgs/posts')
    contenido=models.CharField(max_length=5000)
    fecha=models.DateTimeField(default=datetime.datetime.now)
    autor=models.CharField(max_length=256)

    def __str__(self) -> str:
        return "%s-%s-%s" %(self.titulo, self.contenido, str(self.fecha))

class Comentario(models.Model):
    post=models.ForeignKey(
        Posteo,
        on_delete=models.CASCADE
    )
    contenido=models.CharField(max_length=5000)
    fecha=models.DateTimeField(default=datetime.datetime.now)
    autor=models.CharField(max_length=256)

    def __str__(self) -> str:
        return "%s: %s - %s" % (self.autor, self.contenido, str(self.fecha))

class RespuestaComentario(models.Model):
    comentario=models.OneToOneField(
        Comentario,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    contenido=models.CharField(max_length=5000)
    fecha=models.DateTimeField(default=datetime.datetime.now)
    autor=models.CharField(max_length=256)

    def __str__(self) -> str:
        return "%s: %s - %s" % (self.autor, self.contenido, str(self.fecha))

AppBlog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from AppLogin.models import Usuario

class CrearPostForm(forms.Form):
    titulo = forms.CharField(max_length=50)
    contenido = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))
    imagen = forms.FileField()


class EditarDatosForm(forms.Form):
    email = forms.EmailField(max_length=256, required=False)
    imagen = forms.FileField(required=False, widget=forms.FileInput)
    descripcion = forms.CharField(widget=forms.Textarea(attrs={'rows':3}), required=False)
    link = forms.URLField(max_length=256, required=False)

    class Meta(UserCreationForm.Meta):
        model = Usuario
        fields = UserCreationForm.Meta.fields + ("imagen", "descripcion", "link")


class CambiarContraseniaForm(PasswordChangeForm):
    class Meta:
        model = Usuario

AppBlog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import update_session_auth_hash
from .forms import CrearPostForm, EditarDatosForm, CambiarContraseniaForm
from .models import Posteo, Comentario, RespuestaComentario
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.
def home(request):
    posts = Posteo.objects.all
    return render(request, "AppBlog/home.html", {"logeado":request.user.is_authenticated, "es_admin":request.user.is_staff, "posts":posts})


def posts(request):
    if request.user.is_authenticated and request.user.is_staff:
        if request.method == "POST":
            form = CrearPostForm(request.POST, request.FILES)
            if form.is_valid():
                titulo = request.POST['titulo']
                contenido = request.POST['contenido']
                imagen = request.FILES['imagen']
                post = Posteo (titulo=titulo, contenido=contenido, autor=request.user.username, imagen = imagen)
                post.save()
                return redirect(reverse('Home'))
        else:
            form = CrearPostForm()
        return render(request, "AppBlog/crear_post.html", {"logeado":request.user.is_authenticated, "es_admin":request.user.is_staff, "form": form})
    else:
        return redirect(reverse('Home'))


def puede_comentar_post(request):
    return request.user.is_authenticated and not request.user.is_staff


def post(request, post_id):
    posteo = Posteo.objects.get(id=post_id)
    return render(request, "AppBlog/post.html", { "logeado":request.user.is_authenticated, "es_admin": request.user.is_staff, "post":posteo , "puede_comentar": puede_comentar_post(request) })


@login_required(login_url="Login")
@permission_required("is_staff", raise_exception=True)
def borrar_post(request, post_id):
    posteo = Posteo.objects.get(id=post_id)
    posteo.delete()
    return redirect(reverse('Home'))


@login_required(login_url="Login")
def comentar_post(request, post_id):
    posteo = Posteo.objects.get(id=post_id)
    contenido = request.POST['contenido']
    comentario = Comentario (post = posteo, contenido = contenido, autor = request.user.username)
    comentario.save()
    return redirect(reverse('Posteo', kwargs={ "post_id": post_id }))


@login_required(login_url="Login")
@permission_required("is_staff", raise_exception=True)
def borrar_comentario(request, comentario_id):
    comentario = Comentario.objects.get(id=comentario_id)
    posteo = comentario.post
    comentario.delete()
    return redirect(reverse('Posteo', kwargs={ "post_id": posteo.id }))


@login_required(login_url="Login")
@permission_required("is_staff", raise_exception=True)
def responder_comentario(request, comentario_id):
    contenido = request.POST['contenido']
    comentario = Comentario.objects.get(id=comentario_id)
    posteo = comentario.post
    respuesta = RespuestaComentario (comentario = comentario, contenido = contenido, autor = request.user.username)
    respuesta.save()
    return redirect(reverse('Posteo', kwargs={ "post_id": posteo.id }))


@login_required(login_url="Login")
@permission_required("is_staff", raise_exception=True)
def borrar_respuesta(request, comentario_id):
    comentario = Comentario.objects.get(id=comentario_id)
    posteo = comentario.post
    comentario.respuestacomentario.delete()
    return redirect(reverse('Posteo', kwargs={ "post_id": posteo.id }))


@login_required(login_url="Login")
def perfil(request):
    return render(request, "AppBlog/perfil.html", { "logeado":request.user.is_authenticated, "es_admin": request.user.is_staff, "perfil": request.user })


@login_required(login_url="Login")
def editar_datos(request):
    usuario = request.user
    datos_usuario = {
            'email': usuario.email,
            'imagen': usuario.imagen,
            'descripcion': usuario.descripcion,
            'link': usuario.link
    }
    if request.method == "POST":
        form = EditarDatosForm(request.POST, request.FILES, initial=datos_usuario)
        if form.is_valid():
            nuevo_email = form.cleaned_data.get('email')
            nueva_descripcion = form.cleaned_data.get('descripcion')
            nuevo_link = form.cleaned_data.get('link')
            nueva_imagen = form.cleaned_data.get('imagen')
            usuario.email = nuevo_email
            usuario.descripcion = nueva_descripcion
            usuario.link = nuevo_link
            usuario.imagen = nueva_imagen
            usuario.save()
            return redirect(reverse('VerPerfil'))
    else:
        form = EditarDatosForm(initial=datos_usuario)
    return render(request, "AppBlog/perfil.html", { "logeado":request.user.is_authenticated, "es_admin": request.user.is_staff, "perfil": usuario, "form": form })


@login_required(login_url="Login")
def cambiar_contrasenia(request):
    usuario = request.user
    if request.method == "POST":
        form = CambiarContraseniaForm(usuario, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, usuario)
            return redirect(reverse('VerPerfil'))
    else:
        form = CambiarContraseniaForm(usuario)
    return render(request, "AppBlog/cambiar_contrasenia.html", { "logeado":request.user.is_authenticated, "es_admin": request.user.is_staff, "form": form })


def acerca_de(request):
    return render(request, "AppBlog/about_us.html", { "logeado":request.user.is_authenticated, "es_admin": request.user.is_staff, "perfil": request.user })

AppBlog/templates/AppBlog/about_us.html
{% extends "AppBlog/base.html" %}
{% load static %}
{% static "" as baseUrl %}
{% block content %}
<div style="max-width:600px; margin:4% auto 5% auto; padding:8px 9px;">
  <section class="about-us">
    <div class="about">
      <img src="{% static 'AppBlog/assets/_discord.png' %}" style="position:absolute; text-align: left; margin-left:-10%; border-radius: 10%;">
      <div class="text">
        <h2>Sobre la autora</h2>
        <h5>Alicia Vera Alice</span></h5>
          <p>Recibida en la carrera de Diseño Gráfico en la Universidad de Buenos Aires. Siempre tuve pasión no sólo por el diseño, si no también por los video juegos, cocinar y la teconología en general.</p>
          <p>Este blog fue realizado como entrega para el curso de Python / Django de Coderhouse. Tiene como objetivo ser un blog de recetas para compartir ideas que ayuden a evitar el eterno loop de la pregunta "¿Qué comemos?".
          </p>
          <p>
            Así que, <h2>¡Elige una entrada al azar, toma nota y a cocinar!</h2>
          </p>
        <div class="data">
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

AppBlog/templates/AppBlog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        {% static "" as baseUrl %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>¿Qué comemos? - Blog de recetas</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'AppBlog/assets/food.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppBlog/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Home' %}">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'AcercaDe' %}">Acerca de la autora</a></li>
                        {% if not logeado %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'Login' %}">Ingresar</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Registro' %}">Registrarse</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'VerPerfil' %}">Perfil</a></li>
                            {% if es_admin %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'Posts' %}">Crear artículo</a></li>
                            {% endif %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'Logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4" style="background-image:url({% static 'AppBlog/assets/quesecome.png' %}); background-size: cover; background-repeat: no-repeat; background-position: center center; ">
            <div class="container">
                <div class="text-center my-5" style="color:white">
                    <h1 class="fw-bolder">¿Qué comemos?</h1>
                    <p class="lead mb-0">El blog de recetas para resolver esa ancestral duda existencial</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
                {% block content %}
                {% endblock %}
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Curso Coderhouse  |  Entrega Python 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppBlog/js/scripts.js' %}"></script>
    </body>
</html>

AppBlog/templates/AppBlog/cambiar_contrasenia.html
{% extends "AppBlog/base.html" %}
{% block content %}
<style>
    .errorlist{list-style: none; color:red;}
</style>
<div style="max-width:600px; margin:3% auto 5% auto">
    <h1>Cambiar contraseña</h1>
    <form class="form-control" action="{% url 'CambiarContrasenia' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div style="text-align:right; padding:4%">
            <input class="btn btn-primary" type="submit" value="Cambiar contraseña" style="width:200px"/>
        </div>  
    </form>
</div>
{% endblock %}

AppBlog/templates/AppBlog/comentario_template.html
    <div class="text-muted fst-italic mb-2"><b style="color:black; font-style: normal;">Comentario por {{ comentario.autor }} </b>· {{ comentario.fecha }}</div>
    <p class="mb-2">
        {{ comentario.contenido }}
    </p>

AppBlog/templates/AppBlog/crear_post.html
{% extends "AppBlog/base.html" %}
{% block content %}
<div style="text-align: center; margin-top:4%; margin-bottom:5%;">
    <h3>Crea y publica un artículo</h3>
    <h5>Para crear un artículo ten en cuenta que la imagen es obligatoria.</h5><br>
    <form class="form-control" enctype="multipart/form-data" action="{% url 'Posts' %}" method="POST" style="padding:2%; max-width: 50%; margin: auto;">
        {% csrf_token %}
            {{ form.as_p }}
        
        <br>
        <input class="btn btn-primary" type="submit" value="Publicar"/>
    </form>
</div>
{% endblock %}

AppBlog/templates/AppBlog/home.html
{% extends "AppBlog/base.html" %}
{% load static %}
{% block content %}
    {% if mensaje %}
    <h1>{{ mensaje }}</h1>
    {% endif %}
    {% if posts %}
    <div style="display: grid; padding: 10px; grid-row-gap: 5px; grid-column-gap: 5px; grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); justify-content: center;">
        {% for post in posts %}
            {% load temploader %}
            {% post_template_reducido post %}
        {% endfor %}
    </div>
    {% else %}
    <div style="margin:auto; text-align: center; padding:5%">
        <img src="{% static 'AppBlog/assets/warning-sign.svg' %}" style="width:150px; height:150px; margin-bottom:5%">
        <h1>Oops!</h1>
        <h3>Actualmente no hay ningún artículo cargado en el blog.</h3>
    </div>
    {% endif %}
{% endblock %}

AppBlog/templates/AppBlog/perfil.html
{% extends "AppBlog/base.html" %}
{% block content %}
    {% load static %}
    {% static "" as baseUrl %}
    {% if form %}
        <style>
            .errorlist{list-style: none; color:red;}
        </style>
        <div style="max-width:600px; margin:2% auto 2% auto; padding:8px 9px;">
            <h2>Editar perfil</h2><br>
            <form class="form-control" enctype="multipart/form-data" action="{% url 'EditarDatos' %}" method="POST">
                {% csrf_token %}
                <h3 style="margin:2% none 2% none">Nombre: <b>{{ perfil.username }}</h3>
                {{ form.as_p }}
                <div style="text-align:right; padding:4%">
                    <input class="btn btn-primary" type="submit" value="Guardar" style="width:200px"/>
                </div>
            </form>
        </div>
    {% else %}
        {% load temploader %}
        {% perfil_template perfil %}
    {% endif %}
{% endblock %}

AppBlog/templates/AppBlog/perfil_template.html
{% load static %}
{% static "" as baseUrl %}
<div style="max-width:600px; margin:5% auto 10% auto;">
    <div class="row" style="background-color: #f0f0f0; border-radius: 20px; padding:5px">
        <div style="position:relative; width:200px; height:200px">
            {% if perfil.imagen %}
                <img style=" object-fit: contain; width:200px; height:200px; border-radius: 10%;" src="{{ baseUrl }}{{perfil.imagen.name}}"></img>
            {% endif %}
        </div>
        <div style="position:relative; max-width:400px; padding-left:5%;">
            <h2 style="margin-top:5%">{{ perfil.username }}</h2>
            <h6 class="text-muted">{{ perfil.descripcion }}</h6>
            <a href="{{ perfil.link }}" style="text-decoration: none; font-size:small" target="_blank">Visita mi página personal</a>
        </div>
    </div>
    <div style="text-align: right; margin-top:5%">
        <a class="btn btn-primary" href="{% url 'EditarDatos' %}">Editar datos</a>
        <a class="btn btn-primary" href="{% url 'CambiarContrasenia' %}">Cambiar contraseña</a>
    </div>
</div>

AppBlog/templates/AppBlog/post.html
{% extends "AppBlog/base.html" %}
{% block content %}
    <div class="container mt-5">
            <div class="col-lg-12">
                <section class="mb-5">
                    <figure class="mb-4">
                        <img class="img-fluid rounded" style="border:1px solid #000000; object-fit: contain; width:100%; height:100%;" src="{{ baseUrl }}{{post.imagen.name}}"></img>
                    </figure>
                    {% load temploader %}
                    {% post_template post %}
                </section>
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        {% if puede_comentar %}
                            <form class="mb-4" action="{% url 'ComentarPost' post.id %}" method="POST">
                                {% csrf_token %}
                                <p>Comentario <textarea class="form-control" rows="3" name="contenido"></textarea></p>
                                <input type="submit" value="Comentar"/>
                            </form>
                        {% endif %}

                        {% if post.comentario_set.count > 0 %}
                            {% for comentario in post.comentario_set.all %}
                                {% load temploader %}
                                {% comentario_template comentario %}
                                {% if es_admin %}
                                <div>
                                    <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'BorrarComentario' comentario.id %}">Borrar!</a>
                                </div>
                                {% endif %}
                                {% if comentario.respuestacomentario %}
                                    <ul>
                                            {% load temploader %}
                                            {% respuesta_comentario_template comentario %}
                                            {% if es_admin %}
                                                <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'BorrarRespuesta' comentario.id %}">Borrar!</a>
                                            {% endif %}
                                    </ul>
                                {% elif es_admin %}
                                    <form action="{% url 'ResponderComentario' comentario.id %}" method="POST">
                                        {% csrf_token %}
                                        <p>Respuesta<textarea class="form-control" rows="2" name="contenido"></textarea></p>
                                        <input class="btn btn-primary" type="submit" value="Responder"/>
                                    </form>
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <h7 class="text-muted"><i>Aún no hay comentarios</i></h7>
                        {% endif %}
                    </div>
                </div>
            </section>
                <div style="margin-bottom: 5%; text-align: right;">
                    {% if es_admin %}
                        <a class="btn btn-primary" style="background-color: red;" href="{% url 'BorrarPost' post.id %}">Borrar artículo</a>
                    {% endif %}
                </div>
            </div>
    </div>
{% endblock %}

AppBlog/templates/AppBlog/post_template.html
<article>
    <header class="mb-4">
        <h1 class="fw-bolder mb-1">{{ posteo.titulo }}</h1>
        <div class="text-muted fst-italic mb-2"><b>Por {{ posteo.autor }} </b>· Publicado el {{ posteo.fecha }}</div>
    </header>
    <section class="mb-5">
        <p class="fs-5 mb-4">
            {{ posteo.contenido }}
        </p>
    </section>
</article>

AppBlog/templates/AppBlog/post_template_reducido.html
{% load static %}
{% static "" as baseUrl %}
<div class="card mb-4" style="max-width:450px;">
    <img class="card-img-top" style="border:1px solid #000000; object-fit: contain; width:100%; height:100%;" src="{{ baseUrl }}{{ posteo.imagen.name }}"></img>
    <div class="card-body">
        <div class="small text-muted"><b>Por {{ posteo.autor }} </b>· Publicado el {{ posteo.fecha }}</div>
        <h2 class="card-title h4">{{ posteo.titulo }}</h2>
        <p class="card-text" style="max-width: 100ch; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
            {{ posteo.contenido }}
        </p>
        <a class="btn btn-primary" href="{% url 'Posteo' posteo.id %}">Leer completo →</a>
    </div>
</div>

AppBlog/templates/AppBlog/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
<form action="{% url 'Posts' %}" method="POST">
    {% csrf_token %}
    <p>Título <input type="text" name="titulo"></p>
    <p>Contenido <input type="text" name="contenido"></p>
    <input type="submit" value="Publicar"/>
</form>
</body>
</html>

AppBlog/templates/AppBlog/respuesta_comentario_template.html
<div class="form-control" style="margin-top:15px;">
    <div class="text-muted fst-italic mb-2"><b style="color:black; font-style: normal;">Respuesta de {{ comentario.respuestacomentario.autor }} </b>· {{ comentario.respuestacomentario.fecha }}</div>
    <p class="mb-2">
        {{ comentario.respuestacomentario.contenido }}
    </p>
</div>